ALTER TABLE menus MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE ingredients MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE menus ADD UNIQUE (menu);
CREATE INDEX idx_ingredients_name ON ingredients (name);
