<?php

/**
 * Application Configuration
 *
 * This file is auto-generated by deploy.pl from config/*.yaml
 * DO NOT edit this file directly in production - modify your YAML config instead
 */

class Config
{
    // Cutoff Configuration
    // --------------------

    // Cutoff mode: "daily" or "weekly"
    const CUTOFF_MODE = "daily";

    // Timezone for date/time calculations (PHP timezone identifier)
    const TIMEZONE = "America/Los_Angeles";

    // Weekly Mode Settings
    // Used when CUTOFF_MODE = "weekly"
    const WEEKLY_CUTOFF_DAY = "Thursday";    // Day of week when cutoff occurs
    const WEEKLY_CUTOFF_TIME = "23:00";       // Time on that day (HH:MM)
    const WEEKLY_WEEK_START = "Monday";       // First day of meal week

    // Daily Mode Settings
    // Used when CUTOFF_MODE = "daily"
    const DAILY_CUTOFF_TIME = "21:00";        // Daily cutoff time (HH:MM)
    const DAILY_ADVANCE_DAYS = 1;             // Days in advance cutoff applies

    // Size Selection Configuration
    // ----------------------------

    // Available thaali sizes (comma-separated, smallest to largest)
    const THAALI_SIZES = "S,M,L";

    // Size selection mode: "any" or "downgrade-only"
    // "any": Users can select any size
    // "downgrade-only": Users can only select sizes <= their default size
    const SIZE_SELECTION_MODE = "plus-minus-one";
}

?>
