db:
  host: "localhost"
  name: "sffaiz"
  password: "sffaiz-pass"
email:
  admin: "admin@sfjamaat.org"
  contact: "fmb@sfjamaat.org"
  secretary: "secretary@sfjamaat.org"
links:
  planning: "https://form.jotform.com/222676794136163"
  feedback: "https://goo.gl/forms/PTUd1L9ASeVIeNB92"
title:
  secretary: "our Jamaat Secretary"
app:
  name: "Faiz SF"
