name: PHP Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Run tests
      run: ./vendor/bin/phpunit
